// packages/demo-vue/src/components/DemoPage.vue
<script setup lang="ts">
import type { VNode } from 'vue'

/** The page root: a slot and nothing else. An ordinary Vue component that knows no GenoaCMS. */
defineProps<{ body: VNode[] }>()
</script>

<template>
  <main class="page"><component :is="child" v-for="(child, i) in body" :key="i" /></main>
</template>

// packages/demo-svelte/src/components/DemoPage.svelte
<script lang="ts">
  import type { ResolvedNode } from '@genoacms/sdk'
  import GenoaChildren from '../genoa/GenoaChildren.svelte'

  /** The page root: a slot and nothing else. An ordinary Svelte component that knows no GenoaCMS. */
  const { body }: { body: readonly ResolvedNode[] } = $props()
</script>

<main class="page"><GenoaChildren nodes={body} /></main>
