// packages/demo-vue/src/components/DemoSection.vue
<script setup lang="ts">
import type { VNode } from 'vue'

/** A titled region holding other components — what makes the tree nest. */
defineProps<{ heading: string, content: VNode[] }>()
</script>

<template>
  <section class="section">
    <h2 class="section-heading">{{ heading }}</h2>
    <component :is="child" v-for="(child, i) in content" :key="i" />
  </section>
</template>

// packages/demo-svelte/src/components/DemoSection.svelte
<script lang="ts">
  import type { ResolvedNode } from '@genoacms/sdk'
  import GenoaChildren from '../genoa/GenoaChildren.svelte'

  /** A titled region holding other components — what makes the tree nest. */
  const { heading, content }: { heading: string, content: readonly ResolvedNode[] } = $props()
</script>

<section class="section">
  <h2 class="section-heading">{heading}</h2>
  <GenoaChildren nodes={content} />
</section>
